ChatTriggers/ctjs

build.gradle.kts, src/main/java/com/chattriggers/ctjs/mixins/ChunkAccessor.java, src/main/java/com/chattriggers/ctjs/mixins/ClientChunkManagerAccessor.java, src/main/java/com/chattriggers/ctjs/mixins/ClientChunkMapAccessor.java, src/main/java/com/chattriggers/ctjs/mixins/ClientWorldAccessor.java, src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/World.kt, src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/entity/BlockEntity.kt, src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/world/Chunk.kt, src/main/kotlin/com/chattriggers/ctjs/utils/typealiases.kt, src/main/resources/chattriggers.accesswidener, src/main/resources/chattriggers.mixins.json, src/main/resources/fabric.mod.json
Re-adds ways to get all block entities via world or chunk
Haven't tested whether these work yet, but just wanted to get this out there
=> Wrappers: Add BlockEntity

src/main/kotlin/com/chattriggers/ctjs/engine/ILoader.kt, src/main/kotlin/com/chattriggers/ctjs/engine/IRegister.kt, src/main/kotlin/com/chattriggers/ctjs/engine/langs/js/JSLoader.kt, src/main/kotlin/com/chattriggers/ctjs/engine/module/ModuleManager.kt, src/main/kotlin/com/chattriggers/ctjs/triggers/ChatTrigger.kt, src/main/kotlin/com/chattriggers/ctjs/triggers/ClassFilterTrigger.kt, src/main/kotlin/com/chattriggers/ctjs/triggers/EventTrigger.kt, src/main/kotlin/com/chattriggers/ctjs/triggers/RegularTrigger.kt, src/main/kotlin/com/chattriggers/ctjs/triggers/Trigger.kt, src/main/kotlin/com/chattriggers/ctjs/triggers/TriggerType.kt, src/main/resources/assets/chattriggers/js/moduleProvidedLibs.js
=> Allow users to register custom triggers

src/main/java/com/chattriggers/ctjs/mixins/ClientPlayerInteractionManagerMixin.java, src/main/kotlin/com/chattriggers/ctjs/engine/IRegister.kt, src/main/kotlin/com/chattriggers/ctjs/minecraft/CTEvents.kt, src/main/kotlin/com/chattriggers/ctjs/minecraft/listeners/ClientListener.kt, src/main/kotlin/com/chattriggers/ctjs/triggers/TriggerType.kt
Not really a point to have both these and a PlayerInteract, so just merged them all together
=> Triggers: Remove HitBlock and BreakBlock

src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/World.kt, src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/world/Chunk.kt
If I am looking correctly, these should be the last methods needed to be implemented!!!
=> A handful of World and Chunk changes

src/main/resources/assets/chattriggers/js/moduleProvidedLibs.js
This used to only replace the first occurrence.
=> ModuleProvidedLibs: Fix getJavaType replacing / with .

src/main/java/com/chattriggers/ctjs/NameTagOverridable.java, src/main/java/com/chattriggers/ctjs/TooltipOverridable.java, src/main/java/com/chattriggers/ctjs/mixins/ItemStackMixin.java, src/main/java/com/chattriggers/ctjs/mixins/PlayerEntityMixin.java, src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/entity/Entity.kt, src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/entity/PlayerMP.kt, src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/inventory/Item.kt
These previously errored since you can't actually cast to a Mixin directly.
=> Fix setNametagName and setLore

src/main/kotlin/com/chattriggers/ctjs/commands/Command.kt, src/main/kotlin/com/chattriggers/ctjs/engine/module/ModuleManager.kt, src/main/kotlin/com/chattriggers/ctjs/engine/module/ModuleUpdater.kt, src/main/kotlin/com/chattriggers/ctjs/launch/DynamicMixinManager.kt, src/main/kotlin/com/chattriggers/ctjs/triggers/CommandTrigger.kt
Also fixes setAliases not resetting aliases every time
=> Fix a few NPEs

src/main/java/com/chattriggers/ctjs/mixins/BossBarHudAccessor.java, src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/BossBars.kt, src/main/resources/assets/chattriggers/js/moduleProvidedLibs.js, src/main/resources/chattriggers.mixins.json
I can also add other ways to get the boss bar, but the name seems like the most reasonable one.
Let me know if you think there should be other methods added as well
=> Wrappers: Add BossBars wrapper

src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/renderer/Renderer.kt, src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/Server.kt, src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/Settings.kt, src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/TabList.kt
This should me my last PR for a while
=> Wrappers: Make Server and TabList implement CTWrapper

api/ctjs.api, build.gradle.kts, src/main/kotlin/com/chattriggers/ctjs/CTJS.kt, src/main/kotlin/com/chattriggers/ctjs/Reference.kt, src/main/kotlin/com/chattriggers/ctjs/commands/CTCommand.kt, src/main/kotlin/com/chattriggers/ctjs/commands/Command.kt, src/main/kotlin/com/chattriggers/ctjs/minecraft/CTEvents.kt, src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/renderer/Image.kt, src/main/kotlin/com/chattriggers/ctjs/minecraft/objects/KeyBind.kt, src/main/kotlin/com/chattriggers/ctjs/minecraft/objects/display/Display.kt, src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/CPS.kt, src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/inventory/action/Action.kt, src/main/kotlin/com/chattriggers/ctjs/triggers/ChatTrigger.kt, src/main/kotlin/com/chattriggers/ctjs/triggers/ClassFilterTrigger.kt, src/main/kotlin/com/chattriggers/ctjs/triggers/Trigger.kt, src/main/kotlin/com/chattriggers/ctjs/triggers/TriggerType.kt, src/main/kotlin/com/chattriggers/ctjs/utils/Config.kt, src/main/kotlin/com/chattriggers/ctjs/utils/InternalApi.kt, src/main/kotlin/com/chattriggers/ctjs/utils/extensions.kt
I'll probably hold off on this until we get closer to releasing beta builds
=> Add public API validation plugin

api/ctjs.api, docs/MIGRATION.md, src/main/java/com/chattriggers/ctjs/NameTagOverridable.java, src/main/java/com/chattriggers/ctjs/TooltipOverridable.java, src/main/java/com/chattriggers/ctjs/mixins/CreativeInventoryScreenMixin.java, src/main/java/com/chattriggers/ctjs/mixins/HandledScreenMixin.java, src/main/java/com/chattriggers/ctjs/mixins/ItemStackMixin.java, src/main/java/com/chattriggers/ctjs/mixins/PlayerEntityMixin.java, src/main/java/com/chattriggers/ctjs/mixins/PlayerScreenHandlerMixin.java, src/main/java/com/chattriggers/ctjs/mixins/ScreenHandlerMixin.java, src/main/kotlin/com/chattriggers/ctjs/minecraft/listeners/ClientListener.kt, src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/Player.kt, src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/entity/PlayerMP.kt, src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/inventory/Inventory.kt, src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/inventory/Item.kt, src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/inventory/ItemType.kt, src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/inventory/Slot.kt
Life is easier when we don't have to wrap empty ItemStacks, so we can just return null via the fromMC method.
=> Item: Add setters and a better constructor

src/main/java/com/chattriggers/ctjs/mixins/MinecraftClientMixin.java
and fix triggering on singleplayer worldjoin
=> Fix `ServerConnect` triggering on singleplayer join

src/main/java/com/chattriggers/ctjs/BoundKeyUpdater.java, src/main/java/com/chattriggers/ctjs/mixins/GameOptionsMixin.java, src/main/kotlin/com/chattriggers/ctjs/CTJS.kt, src/main/kotlin/com/chattriggers/ctjs/console/ConsoleManager.kt, src/main/kotlin/com/chattriggers/ctjs/minecraft/objects/KeyBind.kt, src/main/resources/chattriggers.accesswidener, src/main/resources/chattriggers.mixins.json
This fixes some issues with the current injection point, as various features like KeyBind crashed the game instantly on world load
=> Load modules a bit later

api/ctjs.api, src/main/kotlin/com/chattriggers/ctjs/CTJS.kt, src/main/kotlin/com/chattriggers/ctjs/api/client/KeyBind.kt, src/main/kotlin/com/chattriggers/ctjs/engine/Console.kt, src/main/kotlin/com/chattriggers/ctjs/internal/console/ConsoleHostProcess.kt, src/main/kotlin/com/chattriggers/ctjs/internal/utils/Initializer.kt, src/main/resources/assets/chattriggers/lang/en_us.json
Solves https://discord.com/channels/119493402902528000/1165369829629374505
=> Console: Fix keybind getting reset each game load

src/main/kotlin/com/chattriggers/ctjs/api/Mappings.kt
Hopefully the last mappings issue?
=> Mappings: Fix interface methods not being found

src/main/kotlin/com/chattriggers/ctjs/api/inventory/Item.kt
As mentioned here:
https://discord.com/channels/119493402902528000/1174164006542508093
=> Fix not being able to colorize `Item.draw()`

src/main/kotlin/com/chattriggers/ctjs/api/message/TextComponent.kt
Also turn all string actions to lowercase, otherwise `byName` does not find them
=> Parse TextComponent hover values depending on action

src/main/kotlin/com/chattriggers/ctjs/api/client/KeyBind.kt
Fixes https://discord.com/channels/119493402902528000/1181048013708345465/1181048013708345465
=> KeyBind: Fix custom keybinds not being consumed

src/main/kotlin/com/chattriggers/ctjs/CTJS.kt, src/main/kotlin/com/chattriggers/ctjs/internal/engine/module/ModuleManager.kt, src/main/kotlin/com/chattriggers/ctjs/internal/engine/module/ModuleMetadata.kt, src/main/kotlin/com/chattriggers/ctjs/internal/engine/module/ModuleUpdater.kt
This also adds author as an alias for creator
=> CTJS: Use kotlinx serialization instead of gson

src/main/kotlin/com/chattriggers/ctjs/api/render/Shape.kt
Fixes https://discord.com/channels/119493402902528000/1182131559051055144
=> Shape: Fix rendering being offset by the player's position

api/ctjs.api, src/main/java/com/chattriggers/ctjs/internal/mixins/LivingEntityMixin.java, src/main/java/com/chattriggers/ctjs/internal/mixins/PlayerEntityMixin.java, src/main/kotlin/com/chattriggers/ctjs/api/triggers/TriggerType.kt, src/main/kotlin/com/chattriggers/ctjs/engine/Register.kt, src/main/resources/chattriggers.mixins.json
Somehow forgot to add these months ago...
=> Triggers: Implement EntityDamage and EntityDeath
