ChatTriggers/ctjs

- src/main/kotlin/com/chattriggers/ctjs/commands/CTCommand.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/ChatLib.kt
Also removes the ability to clear multiple chat lines by id using clearChat. Use deleteChat for that functionality.
> ChatLib: Fix editChat & deleteChat not working using Message params

- src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/ChatLib.kt
Once the changes from: #8 but especially: 05e6345ac30099292237d894e25d35dcff44ecfe is merged this will behave the same way it behaves in the 1.8.9 version.
I am not sure if using the `ClientCommandInternals` class is bad (since it is marked as `@ApiStatus.Internal`) but so far that is the only solution i have found to work without doing crazy stuff to get the `FabricClientCommandSource` in order to execute commands on the dispatcher.
Also `Client.getMinecraft().networkHandler?.sendChatCommand(text)` actually sends a `CommandExecution` Packet.
> ChatLib.command now works for client- and server-side command

- src/main/java/com/chattriggers/ctjs/mixins/ClientChunkMapAccessor.java
- src/main/kotlin/com/chattriggers/ctjs/CTJS.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/Player.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/World.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/entity/BlockEntity.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/world/block/BlockPos.kt
Block coordinates always start at the smallest corner, so this was causing BlockPos to be off by 1 block in the x or z axis with a negative coordinate.
There's a few other random commits unrelated to this...
Not too sure about the getUUID() change, but just thought I'd do it to make the API slightly more consistent
> BlockPos: Fix negative coordinates being off by one

- src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/ChatLib.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/renderer/Renderer.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/objects/Sound.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/CTWrapper.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/Client.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/Player.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/Scoreboard.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/Server.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/Settings.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/TabList.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/World.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/entity/BlockEntity.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/entity/Entity.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/entity/LivingEntity.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/entity/Particle.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/entity/PlayerMP.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/entity/Team.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/inventory/Item.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/inventory/ItemType.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/inventory/action/Action.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/inventory/nbt/NBTBase.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/inventory/nbt/NBTTagCompound.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/inventory/nbt/NBTTagList.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/world/Chunk.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/world/block/Block.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/world/block/BlockFace.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/world/block/BlockPos.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/world/block/BlockType.kt
- src/main/kotlin/com/chattriggers/ctjs/triggers/ClassFilterTrigger.kt
- src/main/resources/assets/chattriggers/js/moduleProvidedLibs.js
of course this causes huge breaking changes, but I deprecated some to make the transition a little easier. By the time we are done with 1.19 we should probably remove those deprecated methods altogether.
This also has a breaking change making the Entity constructor protected.  This helps development and users by forcing them to instantiate the most narrow wrapper according to the MC class.
> Wrappers: Add CTWrapper class

- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/Settings.kt
Saw [this commit](https://github.com/ChatTriggers/ctjs/commit/fde3c475aa16cff6882a61969a8c6f86229bee7e), so decided to do the same for Settings' objects.
> Settings: Make sub-objects accessible from JS

- src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/renderer/Renderer.kt
- src/main/kotlin/com/chattriggers/ctjs/minecraft/libs/renderer/Text.kt
Add a color parameter that has a default (Renderer.WHITE) to the drawString and drawStringWithShadow methods.
Update Text to utilise this change.
Fixed provided packages not working.
> Color parameter in #drawString

- src/main/kotlin/com/chattriggers/ctjs/console/RemoteConsoleHost.kt
This was a funny bug causing console processes to pile up
> RemoteConsoleHost: Destroy process on game close

- .github/workflows/javadocs.yml
- build.gradle.kts
~All the files are committed to support multiversion docs. Is there any way to not commit these to the repo? Or at least exclude them from the contributors graph in GitHub (not that it really matters)~ Files are now downloaded from the server
> Add javadocs generation via Dokka

- src/main/kotlin/com/chattriggers/ctjs/launch/DynamicMixinManager.kt
Before one had to manully delete the generated `.class` files while in dev environment.
> DynamicMixinManager: add `deleteOldMixinClasses`

- src/main/kotlin/com/chattriggers/ctjs/launch/generation/InjectorGenerator.kt
If you injected multiple times in the same method, the mixin's method name would be the same. This fixes that issue.
> Mixins: Force unique names for generated methods

- src/main/java/com/chattriggers/ctjs/Skippable.java
- src/main/java/com/chattriggers/ctjs/mixins/ItemStackMixin.java
- src/main/kotlin/com/chattriggers/ctjs/minecraft/wrappers/inventory/Item.kt
This also fixes it returning null in most cases, as getHolder refers to the ItemFrame holding it, not the player.
Not sure how brittle this is or if there's a better way to do this.
Fabric's event is injected at the tail of `getTooltip`, so this just circumvents that from triggering.
> Item: Fix getLore triggering the fabric's tooltip event

- src/main/java/com/chattriggers/ctjs/internal/mixins/KeyBindingAccessor.java
- src/main/kotlin/com/chattriggers/ctjs/api/client/KeyBind.kt
wasPressed() consumes the click, but we  really only want to check if the key was pressed, not do anything else with it
> KeyBind: Fix isPressed() sometimes blocking default keybind actions

- src/main/kotlin/com/chattriggers/ctjs/api/client/KeyBind.kt
Previously holding down a key for several seconds caused the onKeyPress to trigger repeatedly.
> KeyBind: Fix multiple key presses triggered from one long press

- src/main/java/com/chattriggers/ctjs/internal/mixins/MinecraftClientMixin.java
- src/main/kotlin/com/chattriggers/ctjs/CTJS.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/console/ConsoleHostProcess.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/engine/module/ModuleManager.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/utils/Initializer.kt
This reverts parts of  64525a3ededa95a414f99e78b91d87fabed35e06 and f19bec16624852ea4768f054160429948b8d415b. Keybinds aren't an issue anymore as the mixin runs after `MinecraftClient::options` is set.
Now gameLoad and top level in the module don't matter much, but the top level runs right before the gameload triggers.
```js
println("above");
register("gameLoad", () => {
println("game loaded");
});
println("below");
```
always outputs
```
above
below
game loaded
```
even on subsequent /ct loads
> CTJS: Load modules earlier, allowing for initial gameLoad to trigger

- src/main/kotlin/com/chattriggers/ctjs/internal/engine/JSLoader.kt
For some reason, we were storing two Context variables and using them throughout the loader. Instead, we should store two scopes (for eval and modules) and use whichever Context happens to be in use on the thread at any particular point.
> JSLoader: Rework Context usage a bit

- build.gradle.kts
- src/main/kotlin/com/chattriggers/ctjs/internal/engine/JSLoader.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/launch/Descriptor.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/launch/DynamicMixinManager.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/launch/InvokeDynamicSupport.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/launch/annotations.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/launch/generation/DynamicMixinGenerator.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/launch/generation/GenerationContext.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/launch/generation/InjectGenerator.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/launch/generation/InjectorGenerator.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/launch/generation/ModifyArgGenerator.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/launch/generation/ModifyArgsGenerator.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/launch/generation/ModifyConstantGenerator.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/launch/generation/ModifyExpressionValueGenerator.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/launch/generation/ModifyReceiverGenerator.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/launch/generation/ModifyReturnValueInjector.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/launch/generation/ModifyVariableGenerator.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/launch/generation/RedirectGenerator.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/launch/generation/Utils.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/launch/generation/WrapOperationGenerator.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/launch/generation/WrapWithConditionGenerator.kt
- src/main/resources/assets/chattriggers/js/mixinProvidedLibs.js
Initially it made sense to crash, but after some experience this is not
a viable solution. There is usually a bit of time between when the mixin
is created and when `.attach()` is called. If the mixin attempts to run
in between this period, it would lead to a crash, however this is not
user error.
To fix this, all generated mixins now check with `JSLoader` to see if
they have an attached method before attempting to invoke it. If there is
no attached method yet, the mixin will act as if it did not exist (e.g.
do nothing for inject mixins, call the original method for redirect
mixins, etc).
With this change, CT users can now inject into places that are invoked
early in the startup process, such as `MinecraftClient.setScreen` (which
is invoked in the `MinecraftClient` constructor).
> Mixins: Do not crash when a mixin has no associated handler

- .github/workflows/build.yml
- .github/workflows/javadocs.yml
- build.gradle.kts
This updates the actions and adds back artifact publishing. This also makes it so normal gradle builds do not run the `kspKotlin` task, as from my experience, slows down build times greatly and disallows hot swapping to debug. If you want to build and run `kspKotlin` at the same time, just do `gradlew build -Pfull`, or execute each task individually.
Now the artifacts will be structured like so:
- ChatTriggers-artifacts-sha.zip
- ctjs-3.0.0-beta.jar
- ctjs-3.0.0-beta-sources.jar
- typings.d.ts
closes #106
> GitHub Actions: Include typings.d.ts file

- src/main/kotlin/com/chattriggers/ctjs/api/Mappings.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/launch/DynamicMixinManager.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/launch/generation/GenerationContext.kt
This works for injection points, but doesn't work for access wideners, as it could potentially lead to problems (normal Fabric access wideners don't support non-Minecraft classes).
> Mixins: Allow mixing in to non-Minecraft classes

- src/main/kotlin/com/chattriggers/ctjs/internal/engine/JSLoader.kt
Errors when evalling with the console would actually error, causing the console to be useless for future eval attempts.
> JSLoader: Print the errors instead of throwing when evalling

- src/main/kotlin/com/chattriggers/ctjs/api/message/TextComponent.kt
This now correctly adds siblings of the text instead of only having 1 part containing the entire text content and root style.
> TextComponent: Correctly parse Texts

- api/ctjs.api
- src/main/kotlin/com/chattriggers/ctjs/CTJS.kt
- src/main/kotlin/com/chattriggers/ctjs/api/client/FileLib.kt
- src/main/kotlin/com/chattriggers/ctjs/internal/commands/CTCommand.kt
This should be used in modules instead of Desktop.browse, as this works cross-platform.
Also ignores unknown json keys, as modules using the "$schema" key from CTAutocomplete, etc would fail to load
> FileLib: Add open() method
